CREATE TABLE hardware (
id INTEGER PRIMARY KEY NOT NULL,
name TEXT NOT NULL,
price REAL NOT NULL
);

CREATE TABLE software (
id INTEGER PRIMARY KEY NOT NULL,
name TEXT NOT NULL,
price REAL NOT NULL
);